#!/bin/bash
set -e

if [ "$1" = "configure" ]; then
    systemctl daemon-reload
    systemctl enable wpe-webkit-kiosk.service
    systemctl enable wpe-webkit-kiosk-vnc.service
    systemctl start wpe-webkit-kiosk.service || true
    systemctl start wpe-webkit-kiosk-vnc.service || true
fi
