name: wpe-webkit-kiosk
base: core22
adopt-info: wpe-webkit
summary: WPE WebKit browser engine packaged for fullscreen kiosk applications.
description: |
  WPE WebKit [1] is a lightweight, embedded-focused port of the WebKit browser engine with hardware acceleration and strong multimedia support.

  This snap packages WPE WebKit, the FDO graphics backend, and the Cog [2] web app container in a ready-to-use kiosk mode. Requires `ubuntu-frame` on Ubuntu Core, or a compatible Wayland compositor on desktop systems.

  On Core systems, the browser runs as a service and automatically restarts after compositor refreshes.
  On desktop systems, launch manually with `wpe-webkit-kiosk.cog`.

  1: https://wpewebkit.org
  2: https://github.com/Igalia/cog

confinement: strict
compression: lzo

layout:
  # Relies on cmake install prefix $SNAP/usr, /libexec is not allowed
  /usr/libexec/wpe-webkit-2.0:
    bind: $SNAP/usr/libexec/wpe-webkit-2.0
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cog:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cog
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/wpe-webkit-2.0:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/wpe-webkit-2.0
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/share/zoneinfo-icu:
    bind: $SNAP/usr/share/zoneinfo-icu
  /usr/local/share/fonts: # wpe-webkit: Search ALL the fonts!
    bind: $SNAP/usr/share/fonts

  ### MIR SNIPPET
  # https://github.com/MirServer/iot-example-graphical-snap/blob/a3ce55ec194d05a9bbacf078a651c69752f85450/snap/snapcraft.yaml#L57-L69
  # https://github.com/MirServer/iot-example-graphical-snap/blob/22/main/snap/snapcraft.yaml
  /usr/share/libdrm:
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/graphics/drirc.d
  # Other, generally useful paths
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/sounds:
    bind: $SNAP/usr/share/sounds
  /etc/fonts:
    bind: $SNAP/etc/fonts
  ### END MIR SNIPPET

environment:
  LC_ALL: C.UTF-8
  GST_PLUGIN_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gstreamer-1.0
  GST_PLUGIN_SYSTEM_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gstreamer-1.0
  GST_PLUGIN_SCANNER: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner
  FONTCONFIG_PATH: ${SNAP}/etc/fonts/conf.d
  FONTCONFIG_FILE: ${SNAP}/etc/fonts/fonts.conf
  LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/pulseaudio:${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/blas:${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/lapack

  ### MIR SNIPPET
  # https://github.com/MirServer/iot-example-graphical-snap/blob/a3ce55ec194d05a9bbacf078a651c69752f85450/snap/snapcraft.yaml#L46-L53
  # https://github.com/MirServer/iot-example-graphical-snap/blob/22/main/snap/snapcraft.yaml
  # Other, generally useful environment settings...
  # XDG config
  XDG_CACHE_HOME: $SNAP_USER_COMMON/.cache
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  XDG_CONFIG_DIRS: $SNAP/etc/xdg
  XDG_DATA_DIRS: $SNAP/usr/local/share:$SNAP/usr/share
  # XKB config
  XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb
  ### END MIR SNIPPET

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [armhf]
    build-for: [armhf]
  - build-on: [arm64]
    build-for: [arm64]

plugs:
  ### MIR SNIPPET
  # https://github.com/MirServer/iot-example-graphical-snap/blob/a3ce55ec194d05a9bbacf078a651c69752f85450/snap/snapcraft.yaml#L36-L43
  # https://github.com/MirServer/iot-example-graphical-snap/blob/22/main/snap/snapcraft.yaml
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22
  ### END MIR SNIPPET

slots:
  dbus-cogctl:
    interface: dbus
    bus: system
    name: com.igalia.Cog

apps:
  cog:
    command-chain: &_command-chain
      - bin/graphics-core22-wrapper
      - bin/wayland-launch
      - bin/set-arch-triplet
      - bin/gio-updater
    command: &_command bin/launch-wpe
    environment:
      # XDG config, see https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
      XDG_DATA_HOME: ${SNAP_USER_DATA}/usr/share
      XDG_CONFIG_HOME: ${SNAP_USER_DATA}/.config
      XDG_DATA_DIRS: ${SNAP_USER_COMMON}/usr/share:${SNAP}/usr/share:${XDG_DATA_DIRS}
      XDG_CONFIG_DIRS: ${SNAP}/etc/xdg:$XDG_CONFIG_DIRS
      XDG_CACHE_HOME: ${SNAP_USER_COMMON}/.cache
      # Writable cache for media files. See https://github.com/WebKit/WebKit/blob/b9fedd48387fde72b00ac63364bc447a59749ab8/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp#L2176 and https://matrix.to/#/!CTTPZAhLfjGrOmKckM:matrix.org/$wtBihALd1XnUQUfA6bqJ-q8iD4sghED8LtxlhseH4bg?via=igalia.com&via=matrix.org&via=h6t.eu
      # The default is /var/tmp which should be persisted across reboots. However, since this is a Kiosk browser, we cannot assume that someone will clean that up regularly.
      WPE_SHELL_MEDIA_DISK_CACHE_PATH: ${XDG_CACHE_HOME}
    plugs: &allplugs
      - wayland # Auto-connected
      - opengl # required for libEGL to work
      - network
      - network-bind # Remote inspector
      - upower-observe
      # Manually connected, show up as AppArmor denials but basic browsing seems to work fine without
      - avahi-observe # zeroconf name resolution
      - audio-playback
      - hardware-observe # required for /sys/firmware/acpi/pm_profile and /sys/class/dmi/id/chassis_type access
      - network-manager
      - hostname-control
      - process-control
      - system-observe # required for /proc/zoneinfo access

  daemon:
    command-chain: *_command-chain
    command: *_command
    daemon: simple
    restart-condition: always
    restart-delay: 3s
    plugs: *allplugs
    slots: [dbus-cogctl]
    environment:
      # XDG config, see https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
      XDG_DATA_HOME: ${SNAP_DATA}/usr/share
      XDG_CONFIG_HOME: ${SNAP_DATA}/.config
      XDG_DATA_DIRS: ${SNAP_COMMON}/usr/share:${SNAP}/usr/share:$XDG_DATA_DIRS
      XDG_CONFIG_DIRS: ${SNAP}/etc/xdg:${XDG_CONFIG_DIRS}
      XDG_CACHE_HOME: ${SNAP_COMMON}/.cache
      # Writable cache for media files. See https://github.com/WebKit/WebKit/blob/b9fedd48387fde72b00ac63364bc447a59749ab8/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp#L2176 and https://matrix.to/#/!CTTPZAhLfjGrOmKckM:matrix.org/$wtBihALd1XnUQUfA6bqJ-q8iD4sghED8LtxlhseH4bg?via=igalia.com&via=matrix.org&via=h6t.eu
      # The default is /var/tmp which should be persisted across reboots. However, since this is a Kiosk browser, we cannot assume that someone will clean that up regularly.
      WPE_SHELL_MEDIA_DISK_CACHE_PATH: ${XDG_CACHE_HOME}

  restart-watcher:
    command: bin/watcher
    daemon: simple
    restart-condition: always
    plugs: *allplugs

  list-websettings:
    command-chain: *_command-chain
    command: usr/bin/cog --help-websettings
    plugs: *allplugs

  clear-cache:
    command: bin/clear-cache
    plugs: *allplugs

hooks:
  configure:
    plugs: *allplugs
  install:
    plugs: *allplugs
  post-refresh:
    plugs: *allplugs

parts:
  libwpe:
    source: https://wpewebkit.org/releases/libwpe-1.16.3.tar.xz
    plugin: meson
    meson-parameters:
      - --buildtype=release
      - --prefix=/usr
    build-packages:
      - build-essential
      - libegl1-mesa-dev
      - libxkbcommon-dev
      - meson
    stage-packages:
      - libxkbcommon0

  wpebackend-fdo:
    after: [libwpe]
    # Updated to 1.16.1: DMA-BUF feedback protocol for newer Mesa, NVidia driver support
    source: https://wpewebkit.org/releases/wpebackend-fdo-1.16.1.tar.xz
    plugin: meson
    meson-parameters:
      - --buildtype=release
      - --prefix=/usr
    build-packages:
      - build-essential
      - ccache
      - libegl1
      - libegl-mesa0
      - libegl1-mesa-dev
      - libwayland-egl1
      - libglib2.0-dev
      - libepoxy-dev
      - libxkbcommon-dev
      - libxml2-dev
      - libxslt1-dev
      - libyaml-dev
      - meson
    stage-packages:
      - libegl1-mesa
      - libepoxy0
      - libwayland-egl1
      - libwayland-client0
      - libwayland-server0
      - libxkbcommon0

  wpe-webkit:
    after: [wpebackend-fdo]
    source: https://wpewebkit.org/releases/wpewebkit-2.50.5.tar.xz
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DPORT=WPE
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
      # Use Clang 18 (required by Skia renderer since WebKit 2.46; core22 ships Clang 14 which is too old)
      - -DCMAKE_C_COMPILER=/usr/bin/clang-18
      - -DCMAKE_CXX_COMPILER=/usr/bin/clang++-18
      # Disable documentation builds.
      - -DENABLE_DOCUMENTATION=OFF
      - -DENABLE_INTROSPECTION=OFF
      # We do not need a sandbox when running fully confined.
      - -DENABLE_BUBBLEWRAP_SANDBOX=OFF
      # Disable JPEG-XL, 22.04 does not ship libjxl
      - -DUSE_JPEGXL=OFF
      # Disable libbacktrace dependency, it is not included in 22.04 repositories
      - -DUSE_LIBBACKTRACE=OFF
      # Disable speech synthesis, not needed for kiosk and Flite not in core22
      - -DENABLE_SPEECH_SYNTHESIS=OFF
      # Ensure wpe-webkit finds libWPEBackend-fdo-1.0.so.1
      - -DCMAKE_BUILD_RPATH="${CRAFT_STAGE}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}"
    build-packages:
      - wget
      - gnupg
      - software-properties-common
      - libstdc++-12-dev
      - gperf
      - ninja-build
      - libavif-dev
      - libunibreak-dev
      - libcairo2-dev
      - liblcms2-dev
      - libepoxy-dev
      - libgbm-dev
      - libgcrypt20-dev
      - libgnutls28-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libharfbuzz-dev
      - libicu-dev
      - libjpeg8-dev
      - libopenjp2-7-dev
      - libsoup-3.0-dev
      - libsqlite3-dev
      - libsystemd-dev
      - libtasn1-6-dev
      - libwebp-dev
      - libwoff-dev
      - libxml2-dev
      - libxslt1-dev
      - pkg-config
      - python3
      - ruby-dev
      - unifdef
      - wayland-protocols
      # TODO: Are these still required without the minibrowser?
      - zlib1g-dev
      - libatk1.0-dev
      - libatk-bridge2.0-dev
    stage-packages:
      - freeglut3
      - libatk-bridge2.0-0 # TODO: Required at runtime?
      - libatk1.0-0 # TODO: Required at runtime?
      - libavif13
      - libblas3
      - libcairo2
      - libdrm2
      - libepoxy0
      - libfontconfig1
      - libfreetype6
      - libgbm1
      - libgcrypt20
      - libgl1
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglu1-mesa
      - libglx0
      - libgpm2
      - libgstreamer-gl1.0-0
      - gstreamer1.0-plugins-bad
      - liblcms2-2
      - libharfbuzz-icu0
      - libicu70
      - libjpeg8
      - libopenjp2-7
      - liborc-0.4-0
      - libsoup-3.0-0
      - libsqlite3-0
      - libsystemd0
      - libtasn1-6
      - libwayland-client0
      - libwayland-server0
      - libwebp7
      - libwebpdemux2
      - libwoff1
      - libxml2
      - libxml2-utils
      - libxslt1.1
      - python3
      - ruby
      - v4l-utils
      - zlib1g
      - to amd64:
          - libatomic1
      - to arm64:
          - libatomic1
    override-build: |
      # Install Clang 18 from LLVM repo (core22 only has Clang 14, WebKit 2.50 needs 18+)
      if ! command -v clang-18 >/dev/null 2>&1; then
        wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
        echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main" > /etc/apt/sources.list.d/llvm-18.list
        apt-get update -qq
        apt-get install -y -qq clang-18 lld-18
      fi

      WPE_VERSION=$(grep -E 'SET_PROJECT_VERSION' "$CRAFT_PART_SRC/Source/cmake/OptionsWPE.cmake" | tr -d '[:alpha:]_()' | tr '[:blank:]' '.')

      craftctl set version="$WPE_VERSION"

      # Even-numbered minor versions indicate stable releases. See https://wpewebkit.org/release/schedule/
      WPE_MINOR_VERSION=$(echo "$WPE_VERSION" | cut -d'.' -f2)
      if [ $(( WPE_MINOR_VERSION % 2)) -eq 0 ]; then
        craftctl set grade=stable
      else
        craftctl set grade=devel
      fi

      craftctl default
    override-prime: |
      craftctl default

      # Updates the snap's MIME database, e.g. for PDF.js resources to load properly.
      "$CRAFT_STAGE/usr/bin/update-mime-database" "$CRAFT_STAGE/usr/share/mime"

  # See Source/cmake/WebKitFeatures.cmake for build-time options.
  # See Source/cmake/OptionsWPE.cmake for overrides applied by WPE.
  # See Source/cmake/OptionsWPE.cmake for required packages.
  cog:
    after: [wpe-webkit]
    source: https://wpewebkit.org/releases/cog-0.18.5.tar.xz
    plugin: meson
    meson-parameters:
      # see https://github.com/Igalia/cog/blob/0.16.1/meson_options.txt
      - --buildtype=release
      - --prefix=/usr
      - -Dcog_dbus_control=system
      - -Dplatforms=wayland
      - -Dmanpages=false
    build-packages:
      - meson
      - ninja-build
      - libcairo2-dev
      - libsoup-3.0-dev
      - libxkbcommon-dev
      - libwayland-dev
      - libegl1-mesa-dev
      - libwayland-bin
      - wayland-protocols
    stage-packages:
      # Runtime requirements for cog browser
      - glib-networking # required for SSL/TLS support
      - glib-networking-common
      - glib-networking-services
      - libgles2
      - libslang2 # dep for gstreamer ASCII art modules ¯\_(ツ)_/¯
      - libgpm2 # mouse
      - libgdk-pixbuf2.0-0
      # TODO: Fix zeroconf/Bonjour name resolution, these don't seem to suffice
      - libavahi-core7
      - libavahi-glib1
      - libavahi-common3
      - libavahi-client3
      - libwayland-cursor0
      - libxkbcommon0
      - libegl1
      - libglib2.0-0
      - libsoup-3.0-0
      - libwayland-client0
      - libwayland-egl1
      - freeglut3
      - libglu1-mesa
      - shared-mime-info
    override-prime: |
      craftctl default
      glib-compile-schemas usr/share/glib-2.0/schemas/
      # see https://stackoverflow.com/questions/28953925/glib-gio-error-no-gsettings-schemas-are-installed-on-the-system

  glue:
    plugin: dump
    source: src
    stage-packages:
      - inotify-tools
    organize:
      launcher/*: bin/
      watcher/*: bin/

  ### MIR SNIPPET
  # https://github.com/MirServer/iot-example-graphical-snap/blob/1f69ee310d009f0ea9cbb8654296abc948bafb15/snap/snapcraft.yaml#L75
  wayland-launch:
    plugin: dump
    source: wayland-launch
    override-build: |
      # The plugs needed to run Wayland. (wayland-launch checks them, setup.sh connects them)
      # You may add further plugs here if you want these options
      PLUGS="opengl wayland graphics-core22 audio-playback"
      sed --in-place "s/%PLUGS%/$PLUGS/g" $CRAFT_PART_BUILD/bin/wayland-launch
      sed --in-place "s/%PLUGS%/$PLUGS/g" $CRAFT_PART_BUILD/bin/setup.sh
      craftctl default
    stage-packages:
      - inotify-tools
  ### END MIR SNIPPET

  ### MIR SNIPPET
  # https://github.com/MirServer/iot-example-graphical-snap/blob/a3ce55ec194d05a9bbacf078a651c69752f85450/snap/snapcraft.yaml#L127-L142
  # https://github.com/MirServer/iot-example-graphical-snap/blob/22/main/snap/snapcraft.yaml
  graphics-core22:
    after:
      - libwpe
      - wpebackend-fdo
      - wpe-webkit
      - cog
      - wayland-launch
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22 nvidia-core22
      cd "$CRAFT_PRIME/usr/share/"
      rm -rf bug drirc.d glvnd libdrm lintian man
      rm -rf applications apport bash-completion dbus-1 doc-base doc gtk-doc\
             help pkgconfig libthai metainfo themes thumbnailers xml
    prime:
      - bin/graphics-core22-wrapper
  ### END MIR SNIPPET
